# Generated by Django 2.0 on 2019-03-28 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('choiceId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('courseId', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('questionA', models.CharField(max_length=50)),
                ('questionB', models.CharField(max_length=50)),
                ('questionC', models.CharField(max_length=50)),
                ('questionD', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.CharField(max_length=50)),
                ('courseName', models.CharField(max_length=50)),
                ('isOver', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examId', models.IntegerField()),
                ('courseId', models.CharField(max_length=50)),
                ('isOver', models.IntegerField()),
                ('score', models.IntegerField()),
                ('type', models.IntegerField()),
                ('choiceAnswer', models.CharField(blank=True, max_length=50, null=True)),
                ('fillAnswer', models.CharField(blank=True, max_length=50, null=True)),
                ('choiceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_system.ChoiceQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='FillInTheBlank',
            fields=[
                ('fillId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('courseId', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('courseId', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.CharField(max_length=50)),
                ('grade', models.IntegerField()),
                ('isPass', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.CharField(max_length=50)),
                ('examId', models.IntegerField()),
                ('ip', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MistakesCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.CharField(max_length=50)),
                ('choiceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_system.ChoiceQuestion')),
                ('fillId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_system.FillInTheBlank')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('userId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('userType', models.IntegerField()),
                ('userName', models.CharField(max_length=50)),
                ('passWord', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mistakescollection',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Person_mistake', to='exam_system.Person'),
        ),
        migrations.AddField(
            model_name='history',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Person_history', to='exam_system.Person'),
        ),
        migrations.AddField(
            model_name='grade',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Person_grade', to='exam_system.Person'),
        ),
        migrations.AddField(
            model_name='forum',
            name='answerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_forum', to='exam_system.Person'),
        ),
        migrations.AddField(
            model_name='forum',
            name='questionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_forum', to='exam_system.Person'),
        ),
        migrations.AddField(
            model_name='exam',
            name='fillId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_system.FillInTheBlank'),
        ),
        migrations.AddField(
            model_name='exam',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Person_exam', to='exam_system.Person'),
        ),
        migrations.AddField(
            model_name='course',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_course', to='exam_system.Person'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacherId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_course', to='exam_system.Person'),
        ),
    ]
