# Generated by Django 2.1.7 on 2019-04-26 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('choiceId', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=50)),
                ('questionA', models.CharField(max_length=50)),
                ('questionB', models.CharField(max_length=50)),
                ('questionC', models.CharField(max_length=50)),
                ('questionD', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseId', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=50)),
                ('isOver', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_student', to='exam_system.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('examId', models.AutoField(primary_key=True, serialize=False)),
                ('isOver', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=-1)),
                ('type', models.IntegerField()),
                ('start_time', models.DateTimeField(default='1970-01-01 00:00:00')),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_exam', to='exam_system.Course')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionId', models.IntegerField()),
                ('answer', models.CharField(blank=True, max_length=50, null=True)),
                ('isRight', models.IntegerField(default=-1)),
                ('type', models.IntegerField()),
                ('checkTime', models.IntegerField(default=0)),
                ('examId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_question', to='exam_system.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='FillInTheBlank',
            fields=[
                ('fillId', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
                ('type', models.IntegerField()),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_fill', to='exam_system.Course')),
            ],
        ),
        migrations.CreateModel(
            name='ForumAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('answerTime', models.DateTimeField(default='1970-01-01 00:00:00')),
            ],
        ),
        migrations.CreateModel(
            name='ForumQuestion',
            fields=[
                ('postId', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('postTime', models.DateTimeField(default='1970-01-01 00:00:00')),
                ('topTime', models.DateTimeField(default='1970-01-01 00:00:00')),
                ('answerNum', models.IntegerField(default=0)),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_forum_question', to='exam_system.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('isPass', models.IntegerField()),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_grade', to='exam_system.Course')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('time', models.DateTimeField(default='1970-01-01 00:00:00')),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_history', to='exam_system.Course')),
                ('examId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_history', to='exam_system.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='MistakesCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionId', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_mistake', to='exam_system.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userType', models.IntegerField()),
                ('userName', models.CharField(max_length=50)),
                ('passWord', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mistakescollection',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Person_mistake', to='exam_system.Person'),
        ),
        migrations.AddField(
            model_name='history',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Person_history', to='exam_system.Person'),
        ),
        migrations.AddField(
            model_name='grade',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Person_grade', to='exam_system.Person'),
        ),
        migrations.AddField(
            model_name='forumquestion',
            name='questionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_question', to='exam_system.Person'),
        ),
        migrations.AddField(
            model_name='forumanswer',
            name='answerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_answer', to='exam_system.Person'),
        ),
        migrations.AddField(
            model_name='forumanswer',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_question', to='exam_system.ForumQuestion'),
        ),
        migrations.AddField(
            model_name='exam',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Person_exam', to='exam_system.Person'),
        ),
        migrations.AddField(
            model_name='coursestudent',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_course', to='exam_system.Person'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacherId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_course', to='exam_system.Person'),
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='courseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_question', to='exam_system.Course'),
        ),
    ]
