# Generated by Django 2.2 on 2019-05-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='isready',
            new_name='isReady',
        ),
        migrations.RemoveField(
            model_name='test',
            name='start_time',
        ),
    ]
