# Generated by Django 2.1.7 on 2019-04-01 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('answerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_answer', to='exam_system.Person')),
            ],
        ),
        migrations.CreateModel(
            name='ForumQuestion',
            fields=[
                ('postId', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('courseId', models.CharField(max_length=50)),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_question', to='exam_system.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='forum',
            name='answerId',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='questionId',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.AddField(
            model_name='forumanswer',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_question', to='exam_system.ForumQuestion'),
        ),
    ]
