# Generated by Django 2.0 on 2019-04-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.DateTimeField(default='1970-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='checkTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='isRight',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='forumquestion',
            name='answerNum',
            field=models.IntegerField(default=0),
        ),
    ]
